### ISSUE TITLE
Request timeout error

### ISSUE THREAD

**Issue by voskobovich** [DarkXaHTeP/vk-auth#9]
Запускаю скрипт и через 3-4 секунды вываливается ошибка

```
[Error: Request timeout error]
```

Вот мой файл vk.js

```
var vkAuth = require('vk-auth')(5324751, 'audio');

vkAuth.authorize('+38XXXXXXXXXX', '*********');

vkAuth.on('error', function(err) {
    console.log(err);
});

vkAuth.on('auth', function(tokenParams) {
    console.log(tokenParams);
    //do something with token parameters
})
```

Запускаю так 

```
$ node vk.js
```

**Comment by DarkXaHTeP** [comment]
Сегодня-завтра попробую посмотреть, может вк поменял разметку на странице и теперь какой-то элемент не находится

**Comment by DarkXaHTeP** [comment]
Я обновил модуль в npm до версии 1.0.4, интеграционные тесты теперь проходят. @voskobovich, если можешь, проверь

**Comment by voskobovich** [comment]
Теперь все работает.
Жаль, что я по прежнему получаю ошибку в своем приложении

```
[error_code] => 17
[error_msg] => Validation required: please open redirect_uri in browser
```

Токен ВК привязан к IP. Я думал что получив токен на сервере я смогу отправлять сообщения, но увы(

**Comment by DarkXaHTeP** [comment]
@voskobovich по поводу данной ошибки можно почитать [здесь](https://vk.com/dev/need_validation). Скорее всего запросы к API производятся не с того же ресурса что и аутентификация.
Текущую проблему закрываю

**Comment by DarkXaHTeP** [comment]
@voskobovich еще раз хотелось бы вернуться к твоей проблеме. Насколько я понял, валидация была введена в API версии 5 и выше, как замена captcha_error из ранних версий. С captcha_error можно достаточно легко разобраться - примеры есть даже у меня в соседнем репозитории https://bitbucket.org/darkxahtep/dx-player/src/40b973e1e807d25d05a0f53f7f6c936fb71fbd4a/routes/api/vk.js?at=master&fileviewer=file-view-default
Попробуй явно задать версию API, например 3.0

**Comment by voskobovich** [comment]
Спасибо, попробую!

**Comment by peschanko** [comment]
Приветствую!

Имею следующий код:

```
var vkAuth = require('vk-auth')(appid, '140492191');

vkAuth.authorize(login, password, function(err, tokenParams) {
    console.log(err);
});
```

Параметры login/password передаются верно. Код работал еще месяц назад, но сейчас выдается ошибка:

` [Error: Request timeout error]`

Это может быть связано с тем, что VK снова изменил разметку?

**Comment by DarkXaHTeP** [comment]
@peschanko скорее всего так и есть, завтра постараюсь глянуть. Спасибо

**Comment by DarkXaHTeP** [comment]
@peschanko я запустил тесты и они успешно прошли, а значит разметка не поменялась.
В вот этой строчке кода `var vkAuth = require('vk-auth')(appid, '140492191');` вторым параметром должен передаваться массив со scope для авторизации, а то что указано похоже на айди пользователя или приложения. Возможно проблема в этом

Так же могу предложить запустить тесты локально у себя и завести отдельный Issue если они не пройдут

**Comment by peschanko** [comment]
Спасибо за быстрый ответ. У себя я обнаржил, что успешно access token возвращается только в случае
`var vkAuth = require('vk-auth')(appid, 'friends');`
В других случаях (например, если запросить доступ `wall` или `friends,wall` или `6`) выдается ошибка `[Error: Request timeout error]`. Не знаю, в чем причина, но до этого мой код работал и с параметром `140492191` (сумма всех прав доступа).

**Comment by DarkXaHTeP** [comment]
@peschanko Проблема с разметкой все-таки была. На странице с подтверждением прав доступа. Эта страница отображается не всегда, поэтому тесты ошибку сразу не показали. Я пофиксил эту проблему в версии 1.0.6

**Comment by peschanko** [comment]
Выполнил команду `npm update vk-auth`, после чего, действительно, библиотека стала принимать на вход произвольные права доступа и возвращать `access token`. Большое спасибо за оперативное внесение изменений!
